[package]
name = "rbxts-libraries/rbxts-signal-plus"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
private = true

[dependencies]
Signal = "robloxiandemo/signal@0.1.9"